spring:
  application:
    name: outbox-relay
  datasource:
    url: jdbc:postgresql://localhost:5433/orderdb
    username: order
    password: order
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  kafka:
    bootstrap-servers: localhost:29092

relay:
  batchSize: 50
  pollMs: 500

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  tracing:
    sampling:
      probability: 1.0  # Zipkin 확인용
    propagation:
      type: B3,W3C