server:
  port: 9001

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5433/orderdb
    username: order
    password: order
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  kafka:
    bootstrap-servers: localhost:29092

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka