server:
  port: 9002

spring:
  application:
    name: inventory-service
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: inventory
      auto-offset-reset: earliest
      # 오토컨피그가 아래 직렬화 기본값을 넣지만, 명시해두면 확실함
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  config:
    import: "optional:configserver:http://localhost:8888"
  cloud:
    config:
      fail-fast: true
      retry:
        max-attempts: 6
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.1
    bus:
      destination: springCloudBus   # 기본값이긴 하지만 명시해두면 좋음
    stream:
      # Bus 바인딩 이름은 고정(springCloudBusInput / springCloudBusOutput)
      kafka:
        bindings:
          springCloudBusInput:
            consumer:
              configuration:
                key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
                value.deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
          springCloudBusOutput:
            producer:
              configuration:
                key.serializer: org.apache.kafka.common.serialization.StringSerializer
                value.serializer: org.apache.kafka.common.serialization.ByteArraySerializer

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    org.springframework.kafka: INFO
    org.apache.kafka.clients.consumer: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,refresh,busrefresh
  tracing:
    sampling:
      probability: 1.0  # Zipkin 확인용
    propagation:
      type: B3,W3C