server:
  port: 9004

spring:
  application:
    name: claim-service
  datasource:
    url: jdbc:postgresql://localhost:5434/claimdb
    username: claim
    password: claim
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  kafka:
    bootstrap-servers: localhost:29092

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  tracing:
    sampling:
      probability: 1.0
    propagation:
      type: B3,W3C
